/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,html,js,ts}'],
  theme: {
    extend: {
      fontFamily: {
        mono: ['"JetBrains Mono"', '"Fira Code"', 'Consolas', 'monospace'],
      },
      colors: {
        mchiato: {
          rosewater: '#f4dbd6',
          flamingo: '#f0c6c6',
          pink: '#f5bde6',
          mauve: '#c6a0f6',
          red: '#ed8796',
          maroon: '#ee99a0',
          peach: '#f5a97f',
          yellow: '#eed49f',
          green: '#a6da95',
          teal: '#8bd5ca',
          sky: '#91d7e3',
          sapphire: '#7dc4e4',
          blue: '#8aadf4',
          lavender: '#b7bdf8',
          text: '#cad3f5',
          subtext1: '#b8c0e0',
          subtext0: '#a5adcb',
          overlay2: '#939ab7',
          overlay1: '#8087a2',
          overlay0: '#6e738d',
          surface2: '#5b6078',
          surface1: '#494d64',
          surface0: '#363a4f',
          base: '#24273a',
          mantle: '#1e2030',
          crust: '#181926',
        },
      },
      typography: ({ theme }) => ({
        mchiato: {
          css: {
            '--tw-prose-body': theme('colors.mchiato.subtext0'),
            '--tw-prose-headings': theme('colors.mchiato.text'),
            '--tw-prose-lead': theme('colors.mchiato.subtext1'),
            '--tw-prose-links': theme('colors.mchiato.peach'),
            '--tw-prose-bold': theme('colors.mchiato.text'),
            '--tw-prose-counters': theme('colors.mchiato.overlay1'),
            '--tw-prose-bullets': theme('colors.mchiato.overlay0'),
            '--tw-prose-hr': theme('colors.mchiato.surface0'),
            '--tw-prose-quotes': theme('colors.mchiato.subtext1'),
            '--tw-prose-quote-borders': theme('colors.mchiato.peach'),
            '--tw-prose-captions': theme('colors.mchiato.overlay1'),
            '--tw-prose-code': theme('colors.mchiato.peach'),
            '--tw-prose-pre-code': theme('colors.mchiato.text'),
            '--tw-prose-pre-bg': theme('colors.mchiato.mantle'),
            '--tw-prose-th-borders': theme('colors.mchiato.surface1'),
            '--tw-prose-td-borders': theme('colors.mchiato.surface0'),
            a: { textDecoration: 'underline', textUnderlineOffset: '2px' },
            'code::before': { content: '""' },
            'code::after': { content: '""' },
          },
        },
      }),
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
